import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import robot from "../public/HiRobot.gif";
import profile from "../public/Profile.jpg";
import bitcamp22 from "../public/CF-WebPage.gif";
// import resume from '../public/Resume & Cover Letter- Ramith Wijesinghe.pdf'

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio - Ramith Wijesinghe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav className="fixed w-full bg-white rounded-lg p-5 flex justify-between">
          <div className="flex ">
            <Image src={robot} className="w-10 h-10" />
            <h1 className="text-xl p-3 text-black font-bold font-burtons">
              RAMITH WIJESINGHE
            </h1>
          </div>
          <ul className="flex items-center">
            <li className="font-bold px-5">
              <a href="#about">About</a>
            </li>
            <li className="font-bold px-5">
              <a href="#work">Work</a>
            </li>
            <li className="font-bold px-5">
              <a href="#skills">Skills</a>
            </li>
            <li className="font-bold px-5">
              <a href="#projects">Projects</a>
            </li>
          </ul>
        </nav>
      </header>

      <main className="bg-[#5865F2] px-20  md:px-20 lg:px-40">
        <section id="about">
          <div className="text-center shadow-lg p-10 ">
            <div className="relative mt-20 flex justify-center mx-auto rounded-full mx ">
              <Image src={profile} className="rounded-full" />
            </div>
            <h2 className="text-5xl text-gray-800 py-3 mt-10 font-bold md:text-6xl">
              Ramith Wijesinghe
            </h2>
            <h3 className="text-2xl py-3 font-medium md:text-3xl">
              Undergraduate Student in Information Science
            </h3>
            <p className="text-md py-3 font-medium leading-8 text-white md:text-lg max-w-lg mx-auto">
              I’m interested in the fields of Data Science, Data Analyst,
              Software Development, Web Development, Solution Specialist and
              Game Development. I am aspiring to have great achievements within
              my career and work hard to attain the goals I have set for myself.
              Therefore, I am looking for Internships/job opportunities relating
              to the field of Information and Computer science in order to
              enhance my skills and gain experience.
            </p>
          </div>
        </section>

        <section id="work">
          <div className="text-center shadow-lg p-10 rounded-xl my-5">
            <h2 className="text-4xl py-2 mb-20 font-bold md:text-5xl">
              Work Experience
            </h2>

            <h3 className="text-2xl py-2  font-medium md:text-3xl">
              IT Computer Operator Assistant & Web Developer at IBBR(May 2022 -
              Present)
            </h3>
            <ul className="text-md py-2 mb-10 font-medium text-white md:text-lg max-w-lg mx-auto">
              <li>IT Support for the employees at IBBR.</li>
              <li>Web Development with Laravel, PHP and tailwind CSS.</li>
            </ul>

            <h3 className="text-2xl py-2 font-medium md:text-3xl">
              University of Maryland – TerpEngage Intern(January 2023 - Present)
            </h3>
            <ul className="text-md py-2 mb-10  font-medium text-white md:text-lg max-w-lg mx-auto">
              <li>Salesforce.</li>
              <li>Data Analysis.</li>
              <li>Working with different types of student Data.</li>
              <li>
                Serve as a student UX experts, analyzing current user interfaces
                and suggesting improvements.
              </li>
            </ul>

            <h3 className="text-2xl py-2 font-medium md:text-3xl">
              {" "}
              Bakery Clerk at Costco Wholesale(November 2019 - August 2022)
            </h3>
            <ul className="text-md py-2 mb-10 font-medium text-white md:text-lg max-w-lg mx-auto">
              <li>Sales of Bakery food items to customers.</li>
              <li>Compiling the Bakery Production sheets.</li>
              <li>
                Preparation and packaging of the food items in the department.
              </li>
              <li>Keeping the department clean.</li>
            </ul>
          </div>
        </section>

        <section id="skills">
          <div className="text-center shadow-lg p-10 rounded-xl my-5">
            <h2 className="text-4xl py-2 mb-20 font-bold md:text-5xl">
              Skills
            </h2>
            <div className="grid  grid-cols-4 gap-5 content-between px-10 py-5">
              <div className="bg-white border-black border-4 rounded-md w-20 h-20 my-5">
                <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg" />
              </div>
              <div className="bg-white border-black border-4 rounded-md w-20 h-20 my-5">
                <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg" />
              </div>
              <div className="bg-white border-black border-4 rounded-md w-20 h-20 my-5">
                <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg" />
              </div>
              <div className="bg-white border-black border-4 rounded-md w-20 h-20 my-5">
                <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unity/unity-original.svg" />
              </div>
              <div className="bg-white border-black border-4 rounded-md w-20 h-20 my-5">
                <img src="https://cdn.jsdelivr.net/npm/simple-icons@3.13.0/icons/r.svg" />
              </div>
              <div className="bg-white border-black border-4 rounded-md w-20 h-20 my-5">
                <img src="https://cdn.jsdelivr.net/npm/simple-icons@3.13.0/icons/laravel.svg" />
              </div>
              <div className="bg-white border-black border-4 rounded-md w-20 h-20 my-5">
                <img src="https://cdn.jsdelivr.net/npm/simple-icons@3.13.0/icons/php.svg" />
              </div>
              <div className="bg-white border-black border-4 rounded-md w-20 h-20 my-5">
                <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg" />
              </div>
              <div className="bg-white border-black border-4 rounded-md w-20 h-20 my-5">
                <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" />
              </div>
            </div>
          </div>
        </section>

        <section id="projects">
          <div className="text-center shadow-lg p-10 rounded-xl my-5">
            <h2 className="text-4xl py-2 mb-20 font-bold md:text-5xl">
              Projects
            </h2>

            <h3 className="text-2xl py-2 font-medium md:text-3xl">
              {" "}
              Class Finder - Bitcamp 2022 (Hackathon)
            </h3>
            <div className="relative flex justify-center mx-auto rounded-full mx ">
              <a href="https://ramareigns.github.io/Website-Bitcam22/">
                <Image src={bitcamp22} className="py-10 cursor-pointer" />
              </a>
            </div>
            <p className="text-md py-2 mb-10  font-medium text-white md:text-lg max-w-lg mx-auto">
              Class Finder is a Website utilized for students in need of finding
              study areas around campus, mainly classrooms. The main premise
              being that through this website they can find out empty classrooms
              around the area with the respective times. They also get access to
              the option of reserving the classrooms beforehand for easy access.
              This Website was built by me and three other students during the
              Hackathon event. We mainly used HTML and CSS with a bit of
              understanding on Cockroach DB databases.
            </p>
            <h3 className="text-2xl py-2 font-medium md:text-3xl">
              Paycheck Protection Program - Info Challenge 2022
            </h3>
            <p className="text-md py-2 mb-10  font-medium text-white md:text-lg max-w-lg mx-auto">
              I participated in the Annual Infor Challenge 2022 held by the
              University of Maryland. The project topic was Paycheck Protection
              Program and i had to identify, Analyse and calculate similarities
              in the data sets. I used Microsoft Excel as my software.
            </p>
          </div>
        </section>

        <section>
          <div className="text-xl text-center font-medium pt-5">
            <h2>Contact Info</h2>
            <p>Email: rwijesin@terpmail.umd.edu</p>
            <p>Mobile: +1(202)3749320</p>
          </div>

          <div className="text-5xl flex justify-center gap-10 py-10">
            <a href="https://www.linkedin.com/in/ramith-wijesinghe-842bab180/">
              <AiFillLinkedin className="cursor-pointer" />
            </a>
            <a href="https://github.com/Ramareigns">
              <AiFillGithub className="cursor-pointer" />
            </a>
            <a href="https://twitter.com/RamithWijesingh">
              <AiFillTwitterCircle className="cursor-pointer" />
            </a>
          </div>
        </section>
      </main>
    </>
  );
}
